routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\HomeController;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::name('products.')->prefix('products')
    ->group(function () {
        Route::get('/', [ProductController::class, 'index'])->name('index')->middleware('auth');
        Route::post('/', [ProductController::class, 'store'])->name('store')->middleware('auth');
        Route::get('/create', [ProductController::class, 'create'])->name('create')->middleware('auth');
        Route::get('/{id}', [ProductController::class, 'show'])->name('show')->middleware('auth');
        Route::get('/{id}/edit', [ProductController::class, 'edit'])->name('edit')->middleware('auth');
        Route::delete('/{id}', [ProductController::class, 'destroy'])->name('delete')->middleware('auth');
        Route::put('/{id}', [ProductController::class, 'update'])->name('update')->middleware('auth');
    });

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'products';
    protected $fillable = ['name', 'contents'];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Models\Product;

class ProductController extends Controller
{
    protected $products;

    public function __construct(Product $products)
    {
        $this->products = $products;
    }

    public function index()
    {
        $products = $this->products->latest()->paginate();
        return view('products.index', compact('products'));
    }

    public function show($id)
    {
        $products = $this->products->findOrFail($id);
        return view('products.show', compact('products'));
    }

    public function store(StoreProductRequest $request)
    {
        $this->products->create($request->all());
        return redirect()->route('products.index');
    }

    public function create()
    {
        return view('products.create');
    }

    public function destroy($id)
    {
        $products = $this->products->findOrFail($id);
        $products->delete();
        return redirect()->route('products.index');
    }

    public function edit($id)
    {
        $products = $this->products->findOrFail($id);
        return view('products.edit', compact('products'));
    }

    public function update(UpdateProductRequest $request, $id)
    {
        $products = $this->products->findOrFail($id);
        $products->update($request->all());
        return redirect()->route('products.index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('products')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Dashboard') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        {{ __('You are logged in!') }}
                    </div>
                    <a href="{{route('products.index')}}" class="btn btn-dark">Go To Index</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Scripts -->

</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav me-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ms-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @endif

                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('products')
    </main>
</div>
</body>
</html>

resources/views/products/create.blade.php
@extends('layouts.app')
@section('products')
    <div class="container">
        <a href="{{route('products.index')}}" class="btn btn-dark">Go Back</a>
        <div class="row justify-content-center">
            <div class="col-row-8">
                <h2>Tasks Insert</h2> <br>
                <form action="{{route('products.store')}}" method="POST">
                    @csrf
                    <div class="card-header">
                        <input type="text" class="form-group" name="name" placeholder="Please insert name ">
                        @error('name')
                        <span class="error text-danger" id="name-error" for="name">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="card-body">
                        <input type="text" class="form-group" name="contents" placeholder="Please insert content">
                    </div>
                    <button class="btn btn-success">Bấm để thấy điều bất ngờ !</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('products')
    <div class="container">
        <a href="{{route('products.index')}}" class="btn btn-dark">Go Back</a>
        <div class="row justify-content-center">
            <div class="col-row-8">
                <h2>Tasks Insert</h2> <br>
                <form action="{{route('products.update',$products->id)}}" method="POST">
                    @method('PUT')
                    @csrf
                    <div class="card-header">
                        <input type="text" class="form-group" name="name" value="{{$products->name}}">
                        @error('name')
                        <span class="error text-danger" id="name-error" for="name">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="card-body">
                        <input type="text" class="form-group" name="contents" value="{{$products->contents}}">
                    </div>
                    <button class="btn btn-primary">Bam thu ma xem</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('products')
    <div class="container">
        <a href="{{route('products.create')}}" class="btn btn-dark">Create Task</a>
        <div class="row justify-content-center">
            <table class="table table-striped">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Contents</th>
                    <th>Options</th>
                </tr>
                @foreach($products as $product)
                    @csrf
                    <tr>
                        <th>{{$product->id}}</th>
                        <th>{{$product->name}}</th>
                        <th>{{$product->contents}}</th>
                        <th>
                            <a class="btn btn-success" href="{{route('products.show',$product->id)}}">View</a>
                            <form action="{{route('products.delete',$product->id)}}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger">Delete</button>
                            </form>
                            <a class="btn btn-primary" href="{{route('products.edit', $product->id)}}">Edit</a>
                        </th>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>

@endsection

resources/views/products/show.blade.php
@extends('layouts.app')
@section('products')
    <div class="container">
        <a href="{{route('products.index')}}" class="btn btn-dark">Go Back</a>
        <hr>
        <div class="row justify-content-center">
            @csrf
            <table class="table table-striped">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Contents</th>
                </tr>
                <tr>
                    <th>{{$products->id}}</th>
                    <th>{{$products->name}}</th>
                    <th>{{$products->contents}}</th>
                    <th>
                        <form action="{{route('products.delete',$products->id)}}" method="POST">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-danger">delete</button>
                        </form>
                        <a class="btn btn-primary" href="{{route('products.edit', $products->id)}}">Edit</a>
                    </th>
                </tr>
            </table>
        </div>
    </div>

@endsection